### ISSUE TITLE
Turn recursion off

### ISSUE THREAD

**Issue by antony** [lukeed/totalist#3]
I'm wondering how you feel about the ability to turn recursion off.

The reason being I'd like to use this to load a load of barrels, so all I really need is the top level dir. I know that each directory within it is something I want to load by reaching for its `index.js` file.

I can't flatten it because each dir is a group of different things.

**Comment by lukeed** [comment]
Hey dude, sorry, but this is the entire point of `totalist` 

Sounds like you just want a `fs.readdir` that just goes one level deep. Something like this maybe:

```js
import * as fs from 'fs';
import { join } from 'path';

function keep(dir) {
	let output = [];
	
	fs.readdirSync(dir).forEach(name => {
		if (name === 'index.js') {
			output.push({ dir })
		} else {
			// since (i think) you're only doing 1 level
			// can just manually construct paths for
			// guess-n-check approach (less FS overall)
			let nxt = join(dir, name);
			let file = join(nxt, 'index.js');
			if (fs.existsSync(file)) {
				output.push({ dir: nxt });
			}
		}
	});

	return output;
}
```

Hopefully that helps. You know where to find me if it doesnt haha
